### ISSUE TITLE
Timers fires all at once

### ISSUE THREAD

**Issue by TZilba** [JohnWolfson/Lakea-Stream-Assistant#87]
Not much to add, basically the timer

**Comment by JohnWolfson** [comment]
This issue has been observed during streams, several timers firing at once despite the configuration file having them offset. There were also cases of timers firing twice, it is likely worth reworking the timers to use Task.Delay to fire new events instead of using a new thread to count down the timers every second

**Comment by JohnWolfson** [comment]
An example of the issue can be seen here at 37:30

https://www.twitch.tv/videos/1905696238

**Comment by JohnWolfson** [comment]
Latest commit also fixes issues with callback arguments trying to enter pre-existing keys into argument dictionaries
